version: 1.0.{build}
clone_folder: C:\Users\NyrOne\Desktop\GestureRecognitionDev\GestureRecognitionOpenCv\GestureRecognition
branches:
  # whitelist
  only:
  - R&D
image: Visual Studio 2017

build:
  project: GestureRecognition\GestureRecognition.sln
  verbosity: minimal
   
